language: csharp
solution: Meting4Net.sln

matrix:
  include:
   # - dotnet: 2.1.301
     # mono: none
     # env: DOTNETCORE=2  # optional, can be used to take different code paths in your script
    - mono: latest
    
install:
  - nuget restore Meting4Net.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
    
script:
 # - dotnet restore
 - msbuild /p:Configuration=Release Meting4Net.sln
 # - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./test/NetCore.Tests/bin/Release/netcoreapp2.1/NetCore.Tests.dll
 
os:
  - linux
